plugins { id 'com.android.application' }

android {
    namespace 'com.lockguard.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.lockguard.app'
        minSdk 26
        targetSdk 35
        versionCode 703
        versionName '0.7.03'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
}
