(()=>{
const IS_LOCKGUARD=location.hostname==='lockguardapp.vercel.app';
if(IS_LOCKGUARD){window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.source!=='lockguard-web')return;if(e.data.type==='LOCKGUARD_VAULT_SYNC')chrome.runtime.sendMessage({type:'SYNC_VAULT',items:e.data.items||[],version:e.data.version});if(e.data.type==='LOCKGUARD_VAULT_LOCK')chrome.runtime.sendMessage({type:'LOCK_VAULT'});if(e.data.type==='LOCKGUARD_EXTENSION_PING')window.postMessage({source:'lockguard-extension',type:'LOCKGUARD_EXTENSION_READY'},location.origin)});window.postMessage({source:'lockguard-extension',type:'LOCKGUARD_EXTENSION_READY'},location.origin);return}
let btn=null,menu=null;
function passwordField(){return [...document.querySelectorAll('input[type="password"]')].find(x=>x.offsetParent!==null&&!x.disabled&&!x.readOnly)}
function nativeSet(el,value){let p=Object.getPrototypeOf(el),d=Object.getOwnPropertyDescriptor(p,'value');if(d?.set)d.set.call(el,value);else el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}
function userField(pass){let form=pass.form||pass.closest('form')||document,c=[...form.querySelectorAll('input:not([type="password"]):not([type="hidden"]):not([disabled])')].filter(x=>x.offsetParent!==null);return c.find(x=>x.type==='email')||c.find(x=>/user|email|login|account/i.test((x.name||'')+' '+(x.id||'')+' '+(x.autocomplete||'')))||c.filter(x=>['text','email'].includes(x.type)).pop()}
function close(){menu?.remove();menu=null}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fill(item){let p=passwordField();if(!p)return;let u=userField(p);if(u&&item.user)nativeSet(u,item.user);nativeSet(p,item.password);p.focus()}
function openMenu(matches,locked){close();menu=document.createElement('div');menu.className='lg-menu';let title=document.createElement('div');title.className='lg-menu-title';title.textContent=locked?'LOCKGUARD BLOQUEADO':'LOCKGUARD';menu.appendChild(title);if(locked){let x=document.createElement('button');x.textContent='Abrir e desbloquear LockGuard';x.onclick=()=>window.open('https://lockguardapp.vercel.app','_blank');menu.appendChild(x)}else if(!matches.length){let d=document.createElement('div');d.className='lg-empty';d.textContent='Nenhuma credencial correspondente a este site.';menu.appendChild(d)}else matches.forEach(item=>{let x=document.createElement('button');x.innerHTML='<strong>'+escapeHtml(item.name)+'</strong><small>'+escapeHtml(item.user||'sem usuário')+'</small>';x.onclick=()=>{fill(item);close()};menu.appendChild(x)});document.body.appendChild(menu)}
async function click(){let r=await chrome.runtime.sendMessage({type:'GET_MATCHES',url:location.href});openMenu(r?.matches||[],!!r?.locked)}
function ensure(){if(!passwordField()){btn?.remove();btn=null;close();return}if(btn)return;btn=document.createElement('button');btn.type='button';btn.className='lg-fab';btn.title='Preencher com LockGuard';btn.innerHTML='🔒';btn.onclick=e=>{e.preventDefault();e.stopPropagation();click()};document.documentElement.appendChild(btn)}
ensure();new MutationObserver(ensure).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['type','style','class']});document.addEventListener('click',e=>{if(menu&&!menu.contains(e.target)&&e.target!==btn)close()},true);
})();